### ISSUE TITLE
Demo code example is required

### ISSUE THREAD

**Issue by dmitry-trefilov** [j2sg/qt-net-snmp#1]
Hi, Juan Jose Salazar Garcia
 
Can you provide me a simple code example describing how to use your qt-net-snmp library?
I need parse arbitrary mib file, send SET and GET requests with some oids. I build your library and then wrote the following code:
 
```
#include <QCoreApplication>
#include <QVector>
#include "qsnmpoid.h"
#include "qsnmpmanager.h"
 
using namespace QtNetSNMP;
 
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
 
    QSNMPManager *man = QSNMPManager::instance();
    man ->setup(161, 5);
 
    QMIBTree *boo = man->getMIBFile("/home/user/snmp/mibs/BRWAVE-RADIO-MIB.txt");
 
   QVector<QSNMPObject *> getoids;
 
   getoids.append( new QSNMPObject(".1.3.6.1.4.1.6080.1.1.3") ); // <== here error
 
    return a.exec();
}
```
 
but then I got error:

> ../qtnetsnmp_demo/main.cpp: In function ‘int main(int, char**)’:
> ../qtnetsnmp_demo/main.cpp:19:64: error: invalid use of incomplete type ‘class QtNetSNMP::QSNMPObject’
>     getoids.append( new QSNMPObject(".1.3.6.1.4.1.6080.1.1.3.0") );
>                                                                 ^
> In file included from ../qtnetsnmp_demo/main.cpp:4:
> /usr/include/QtNetSNMP/qsnmpmanager.h:41:11: note: forward declaration of ‘class QtNetSNMP::QSNMPObject’
>      class QSNMPObject;
>            ^~~~~~~~~~~

           
How to resolve this trouble?

**Comment by Caglarr** [comment]
Hello :) Not about your question but I'd like to ask you another question, I couldn't handle to build this library. How could I build, there is no make file inside the files.  Thank for your help :)

**Comment by g-rin** [comment]
Hi @Caglarr!
You have to use qmake (you have to have it as it is a Qt based library). It will generate an appropriate Makefile for your OS.
`qmake [options] qt-net-snmp.pro` or just `qmake` in the root folder of the project.

**Comment by Caglarr** [comment]
Hi @g-rin ,
Thanks a lot ! that(qmake) is worked. 
i am appreciative for your help :)

**Comment by g-rin** [comment]
Hi @Caglarr!
I was happy to help.
